### ISSUE TITLE
FEATURE REQUEST: Water and lava modifiers, flight

### ISSUE THREAD

**Issue by masonalexone** [Korbsti/Mythical-Races#1]
Hi! I am trying to abandon another plugin (an origins one) that has gone un-updated for months. The only things missing in this one are the ability to have origins heal/take damage in water and lava, and have some origins fly at night/day or in current biomes, rain, etc. Any chance we could get things like these added?

**Comment by Korbsti** [comment]
Added

**Comment by Korbsti** [comment]
Added the block specific effects customization options - as for the later - in my discord server there will be an "addons" plugin that I will make in the following weeks just join that and the feature will come out soon or a later
